config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/dashboard/', permanent=False)),
    url(r'^statistics/$', TemplateView.as_view(template_name='pages/statistics.html'), name='statistics'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('yosim.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # YOSIM urls
    url(r'^servers/', include('yosim.servers.urls', namespace='servers')),
    url(r'^agents/', include('yosim.agents.urls', namespace='agents')),
    url(r'^rules/', include('yosim.rules.urls', namespace='rules')),
    url(r'^locations/', include('yosim.locations.urls', namespace='locations')),
    url(r'^categories/', include('yosim.categories.urls', namespace='categories')),
    url(r'^signatures/', include('yosim.signatures.urls', namespace='signatures')),
    url(r'^alerts/', include('yosim.alerts.urls', namespace='alerts')),
    url(r'^syschecks/', include('yosim.syschecks.urls', namespace='syschecks')),
    url(r'^dashboard/', include('yosim.dashboard.urls', namespace='dashboard')),
    url(r'^settings/', include('yosim.settings.urls', namespace='settings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

yosim/agents/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.AgentListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^(?P<agent_id>[\w.@+-]+)/$',
        view=views.AgentDetailView.as_view(),
        name='detail'
    )
]

yosim/rules/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.RuleListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^(?P<alert_id>[\w.@+-]+)/$',
        view=views.RuleDetailView.as_view(),
        name='detail'
    )
]

yosim/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

yosim/agents/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from ..servers.models import Server


@python_2_unicode_compatible
class Agent(models.Model):
    name = models.CharField(max_length=64)
    agent_id = models.CharField(max_length=10)
    agent_status = models.CharField(max_length=20)
    ip_address = models.CharField(max_length=46)
    server = models.ForeignKey(Server)
    last_contact = models.IntegerField(null=True)
    version = models.CharField(max_length=32)
    information = models.CharField(max_length=128)

    class Meta:
        db_table = 'agent'

    def __str__(self):
        return "{} - {} - {} - {} - {} - {} - {} - {} - {}".\
            format(self.id, self.name, self.agent_id, self.agent_status,
                   self.ip_address, self.server, self.last_contact,
                   self.version, self.information)

yosim/dashboard/models.py
from django.db import models

# Create your models here.

yosim/settings/models.py
from django.db import models

# Create your models here.

yosim/agents/views.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from .models import Agent


class AgentListView(ListView):
    model = Agent
    template_name = 'agents/agent_list.html'
    context_object_name = 'agents'

    def get_queryset(self):
        return Agent.objects.select_related().all()


class AgentDetailView(DetailView):
    model = Agent
    template_name = 'agents/agent_detail.html'
    context_object_name = 'agent'

    def get_object(self):
        return Agent.objects.select_related().get(
            id=self.kwargs.get("agent_id"))

yosim/alerts/views.py
# -*- coding: utf-8 -*-
import re
import pytz
import json
from dateutil import rrule
from datetime import datetime, timedelta, time
from collections import OrderedDict

from django.db.models import Q
from django.views.generic import View, ListView, DetailView
from django.db.models.expressions import RawSQL
from django.db.models import Count, DateTimeField
from django.db.models.functions import TruncHour, TruncDay, TruncMonth
from django.http import HttpResponse

from .models import Alert
from ..agents.models import Agent
from ..locations.models import Location
from ..signatures.models import SignatureCategoryMapping
from ..categories.models import Category


class AlertListView(ListView):
    model = Alert
    template_name = 'alerts/alert_list.html'
    context_object_name = 'alerts'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(AlertListView, self).get_context_data(**kwargs)
        first_alert = Alert.objects.values('timestamp').\
            order_by('timestamp').first()
        last_alert = Alert.objects.values('timestamp').\
            order_by('timestamp').last()
        tz = pytz.timezone('Asia/Ho_Chi_Minh')
        start_date = datetime.fromtimestamp(first_alert['timestamp'], tz)
        start_date = datetime.combine(start_date.date(), time())
        end_date = datetime.fromtimestamp(last_alert['timestamp'], tz)
        end_date = datetime.combine(end_date.date(), time()) + \
            timedelta(days=1) - timedelta(seconds=1)
        context['start_date'] = start_date.strftime('%d/%m/%Y %I:%M:%S %p')
        context['end_date'] = end_date.strftime('%d/%m/%Y %I:%M:%S %p')
        return context

    def get_queryset(self):
        return Alert.objects.select_related().all().order_by('-timestamp')


class AlertDetailView(DetailView):
    model = Alert
    template_name = 'alerts/alert_detail.html'
    context_object_name = 'alert'

    def get_object(self):
        return Alert.objects.select_related().get(
            id=self.kwargs.get("alert_id"))


class AlertSearchView(ListView):
    model = Alert
    template_name = 'alerts/alert_search.html'
    context_object_name = 'alerts'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(AlertSearchView, self).get_context_data(**kwargs)
        url_encode = self.request.GET.urlencode(True)
        match = re.match(r'([\&\?]page=(\d)+|page=(\d)+\&)', url_encode)
        if match:
            remove = match.group(0)
            url_encode = url_encode.replace(remove, '')
        context['url_encode'] = url_encode
        return context

    def get_queryset(self):
        daterange = self.request.GET.get('daterange', False)
        categories = self.request.GET.getlist('categories', [])
        users = self.request.GET.getlist('users', [])
        hosts = self.request.GET.getlist('hosts', [])
        levels = self.request.GET.getlist('levels', [])
        # locations = self.request.GET.getlist('locations', [])

        daterange_query = Q()
        # locations_query = Q()
        categories_query = Q()
        users_query = Q()
        hosts_query = Q()
        levels_query = Q()

        if daterange:
            start_date, end_date = daterange.split(' - ')
            start_date = datetime.strptime(start_date, '%d/%m/%Y %I:%M %p')
            end_date = datetime.strptime(end_date, '%d/%m/%Y %I:%M %p')
            alerts_daterange_ids = Alert.objects.all().\
                annotate(datetime=RawSQL('FROM_UNIXTIME(timestamp)', [],
                         output_field=DateTimeField())).\
                filter(datetime__gte=start_date, datetime__lte=end_date).\
                values_list('id', flat=True)
            daterange_query = Q(id__in=alerts_daterange_ids)

        if categories:
            rule_ids = SignatureCategoryMapping.objects.\
                filter(cat_id__in=categories).values_list(
                    'rule_id', flat=True).distinct()
            categories_query = Q(rule_id__in=rule_ids)

        if hosts:
            filter_agents = Agent.objects.filter(agent_id__in=hosts)
            for agent in filter_agents:
                if agent.agent_id == '000':
                    loca_filter = agent.name.rstrip(' (server)')
                else:
                    loca_filter = agent.ip_address
                location_ids = Location.objects.\
                    filter(name__icontains=loca_filter).\
                    values_list('id', flat=True)
                host_query = Q(location_id__in=list(location_ids))
                hosts_query |= host_query

        # if locations:
        #     locations_query = Q(location_id__in=locations)
        #
        users_query = Q(user__in=users) if users else Q()
        levels_query = Q(level__in=levels) if levels else Q()

        # combine all Q query
        Qquery = Q(daterange_query & hosts_query & categories_query
                   & users_query & levels_query)
        return Alert.objects.select_related().all().filter(Qquery).\
            order_by('-timestamp')


class AlertStatisticsView(View):
    def post(self, request, *args, **kwargs):
        startDate = request.POST.get('startDate', False)
        endDate = request.POST.get('endDate', False)
        result = {}
        if startDate and endDate:
            start_date = datetime.strptime(startDate, '%d/%m/%Y %I:%M %p')
            end_date = datetime.strptime(endDate, '%d/%m/%Y %I:%M %p')
            alert_with_datetime = Alert.objects.all().\
                annotate(datetime=RawSQL('FROM_UNIXTIME(timestamp)', [],
                         output_field=DateTimeField())).\
                filter(datetime__gte=start_date, datetime__lte=end_date)
            diff = end_date - start_date
            if diff.days == 0:
                trunc_alerts = alert_with_datetime.annotate(
                    hour=TruncHour('datetime')).values('hour').\
                    annotate(count=Count('id')).values_list('hour', 'count')
                trunc_alerts = list(trunc_alerts)
                new_trunc_alerts = []
                for dt in rrule.rrule(
                        rrule.HOURLY, dtstart=start_date, until=end_date):
                    new_trunc_alerts.append([dt, 0])

                for new_alert in new_trunc_alerts:
                    for alert in trunc_alerts:
                        if alert[0].replace(tzinfo=None) == new_alert[0]:
                            new_alert[1] = alert[1]

                result['by_time'] = {
                    'label': 'Number of OSSEC alerts in 24 hours',
                    'count': [item[1] for item in new_trunc_alerts],
                    'data':
                        [item[0].strftime("%H") for item in new_trunc_alerts]
                }
            elif diff.days > 0 and diff.days <= 31:
                trunc_alerts = alert_with_datetime.annotate(
                    date=TruncDay('datetime')).values('date').\
                    annotate(count=Count('id')).values_list('date', 'count')
                trunc_alerts = list(trunc_alerts)
                new_trunc_alerts = []
                for dt in rrule.rrule(
                        rrule.DAILY, dtstart=start_date, until=end_date):
                    new_trunc_alerts.append([dt, 0])

                for new_alert in new_trunc_alerts:
                    for alert in trunc_alerts:
                        if alert[0].replace(tzinfo=None) == new_alert[0]:
                            new_alert[1] = alert[1]

                result['by_time'] = {
                    'label': 'Number of OSSEC alerts per days',
                    'count': [item[1] for item in new_trunc_alerts],
                    'data':
                    [item[0].strftime("%d/%m") for item in new_trunc_alerts]
                }
            elif diff.days > 31 and diff.days <= 365:
                trunc_alerts = alert_with_datetime.annotate(
                    date=TruncDay('datetime')).values('date').\
                    annotate(count=Count('id')).values_list('date', 'count')
                trunc_alerts = list(trunc_alerts)
                new_trunc_alerts = OrderedDict()
                for dt in rrule.rrule(
                        rrule.DAILY, dtstart=start_date, until=end_date):
                    isocalendar = dt.isocalendar()
                    week = 'W{0}/{1}'.format(isocalendar[1], isocalendar[0])
                    if week not in new_trunc_alerts:
                        new_trunc_alerts[week] = {
                            'start_date': dt,
                            'count': 0
                        }
                    else:
                        new_trunc_alerts[week]['end_date'] = dt

                for alert in trunc_alerts:
                    isocalendar = alert[0].isocalendar()
                    week = 'W{0}/{1}'.format(isocalendar[1], isocalendar[0])
                    new_trunc_alerts[week]['count'] = \
                        new_trunc_alerts[week]['count'] + alert[1]

                result['by_time'] = {
                    'label': 'Number of OSSEC alerts per weeks',
                    'count':
                    [item['count'] for item in new_trunc_alerts.values()],
                    'data': list(new_trunc_alerts.keys())
                }
            else:
                trunc_alerts = alert_with_datetime.annotate(
                    month=TruncMonth('datetime')).values('month').\
                    annotate(count=Count('id')).values_list('month', 'count')
                trunc_alerts = list(trunc_alerts)
                new_trunc_alerts = []
                for dt in rrule.rrule(
                        rrule.MONTHLY, dtstart=start_date, until=end_date):
                    new_trunc_alerts.append([dt, 0])

                for new_alert in new_trunc_alerts:
                    for alert in trunc_alerts:
                        if alert[0].replace(tzinfo=None) == new_alert[0]:
                            new_alert[1] = alert[1]

yosim/categories/views.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from .models import Category


class CategoryListView(ListView):
    model = Category
    template_name = 'categories/category_list.html'
    context_object_name = 'categories'
    paginate_by = 10

    def get_queryset(self):
        return Category.objects.all()


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'categories/category_detail.html'
    context_object_name = 'category'

    def get_object(self):
        return Category.objects.get(cat_id=self.kwargs.get("category_id"))

yosim/locations/views.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from .models import Location


class LocationListView(ListView):
    model = Location
    template_name = 'locations/location_list.html'
    context_object_name = 'locations'
    paginate_by = 10

    def get_queryset(self):
        return Location.objects.select_related().all()


class LocationDetailView(DetailView):
    model = Location
    template_name = 'locations/location_detail.html'
    context_object_name = 'location'

    def get_object(self):
        return Location.objects.select_related().get(
            id=self.kwargs.get("location_id"))

yosim/rules/views.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from .models import Rule


class RuleListView(ListView):
    model = Rule
    template_name = 'rules/rule_list.html'
    context_object_name = 'rules'
    paginate_by = 10

    def get_queryset(self):
        return Rule.objects.all().order_by('rule_id')


class RuleDetailView(DetailView):
    model = Rule
    template_name = 'rules/rule_detail.html'
    context_object_name = 'rule'

    def get_object(self):
        return Rule.objects.get(id=self.kwargs.get("rule_id"))

yosim/servers/views.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from .models import Server


class ServerListView(ListView):
    model = Server
    template_name = 'servers/server_list.html'
    context_object_name = 'servers'
    paginate_by = 10

    def get_queryset(self):
        return Server.objects.all()


class ServerDetailView(DetailView):
    model = Server
    template_name = 'servers/server_detail.html'
    context_object_name = 'server'

    def get_object(self):
        return Server.objects.get(id=self.kwargs.get("server_id"))

yosim/templates/settings/control_panel.html
{% extends "base.html" %}

{% load static i18n %}

{% block title %}Control Panel{% endblock %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Control Panel</h1>
</section>

<section class="content">
<div class="row">
    <div class="col-lg-12">
        <!-- Custom Tabs -->
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#syschecks" data-toggle="tab">File Integrity Monitoring</a></li>
                <li><a href="#ossec-service-logs" data-toggle="tab">OSSEC Service Logs</a></li>
            </ul>
            <div class="tab-content">
                <div id="syschecks" class="tab-pane active">
                    {% for host, config in syschk_cfg.items %}
                    <form action="{% url 'settings:update' %}">
                        <h4>
                            <input type="hidden" name="cfg_type" value="{{ host }}">
                            <input type="hidden" name="cfg_fpath" value="{{ config.cfg_fpath }}">
                            <span class="label label-custom label-default">{{ host }}</span>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </h4>
                        <div class="box-body">
                            <div class="row">
                                {% for tag, value in config.items %}
                                    {% if tag != 'cfg_fpath' %}
                                        <div class="col-md-6">
                                            <div class="box box-default">
                                                <div class="box-header with-border">
                                                    <h4 class="box-title">{{ tag }}</h4>
                                                </div>
                                                <div class="box-body">
                                                    {% for key, value in value.items %}
                                                        {% if key == 'directories' %}
                                                            <div class="form-group">
                                                              <label for="{{ key }}">{{ key }}</label>
                                                              <input type="text" class="form-control" name="{{ tag }}_{{ key }}" value="{{ value|join:", " }}" required>
                                                            </div>
                                                        {% comment %}
                                                        {% elif key == 'attributes' %}
                                                            <div class="form-group">
                                                                <label for="{{ key }}">{{ key }}</label>
                                                                {% for key, value in value.items %}
                                                                    <div class="checkbox">
                                                                        <label>
                                                                            <input type="checkbox" name="{{ tag }}_{{ key }}" checked> {{ key }}
                                                                        </label>
                                                                    </div>
                                                                {% endfor %}
                                                            </div>
                                                        {% endcomment %}
                                                        {% endif %}
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </form>
                    {% endfor %}
                </div>
                <div id="ossec-service-logs" class="tab-pane">
                    <div class="pre-scrollable pre-custom">
                        {% for line in ossec_log %}
                            {{ line|linebreaks }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- nav-tabs-custom -->
    </div>
    <!-- /.col -->
</div>
</section>

{% endblock content %}